[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "adafmt"
version = "0.0.0"
description = "Ada Language Formatter (ALS-backed, Customizable)"
authors = [
  { name = "Michael Gardner, A Bit of Help, Inc." }
]
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "typer>=0.9.0",
    "tabulate>=0.9.0",
]

[project.scripts]
adafmt = "adafmt.cli:main"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov",
    "pytest-asyncio",
    "black",
    "mypy",
    "ruff",
]
test = [
    "pytest>=7.0",
    "pytest-asyncio",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
branch = "main"
changelog_file = "CHANGELOG.md"
build_command = "python3 -m build"
tag_format = "v{version}"
commit_message = "{version}\n"

[tool.semantic_release.branches.main]
match = "main"
prerelease = false

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "refactor", "style", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_pypi = true
upload_to_vcs_release = true

[tool.semantic_release.remote]
name = "origin"
type = "github"

