name: release

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # needed for creating tags/releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip and install tools
        run: |
          python -m pip install --upgrade pip
          pip install build python-semantic-release

      - name: Clean dist
        run: rm -rf dist

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          SEMANTIC_RELEASE_LOG_LEVEL: DEBUG
        run: python -m semantic_release publish
