name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install "python-semantic-release>=9,<10"

      - name: Compute next version (noop)
        id: nextver
        run: |
          NV="$(python -m semantic_release --noop version --print)"
          echo "value=$NV" >> "$GITHUB_OUTPUT"

      - name: Update docs/README headers with next version
        run: |
          echo "Next version: ${{ steps.nextver.outputs.value }}"
          SEMVER_NEXT="${{ steps.nextver.outputs.value }}"           python scripts/update_doc_headers.py --write --no-backup
          if ! git diff --quiet -- README.md docs; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md docs
            git commit -m "docs: update headers for v${{ steps.nextver.outputs.value }}"
            git push
          fi

      - name: Run semantic-release publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          SEMANTIC_RELEASE_LOG_LEVEL: DEBUG
        run: python -m semantic_release publish
